import Link from "next/link";
import { FileText, AlertTriangle, Anchor } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto py-10 px-4">
      {/* Header */}
      <div className="flex items-center gap-3 mb-2">
        <div className="w-10 h-10 rounded-xl bg-ocean-600 flex items-center justify-center">
          <FileText size={20} className="text-white" />
        </div>
        <div>
          <h1 className="text-2xl font-bold text-slate-900">Terms of Use</h1>
          <p className="text-xs text-slate-400">Last updated: May 2026</p>
        </div>
      </div>

      {/* Medical disclaimer banner */}
      <div className="mt-6 mb-8 rounded-xl border-2 border-amber-300 bg-amber-50 p-5 flex gap-4">
        <AlertTriangle size={22} className="text-amber-500 shrink-0 mt-0.5" />
        <div>
          <p className="font-bold text-amber-800 text-sm mb-1">Medical Disclaimer — Read First</p>
          <p className="text-sm text-amber-700 leading-relaxed">
            Vessel Ops AI is a <strong>decision-support tool only</strong>. It does not replace the judgment of a
            qualified physician, paramedic, or medical professional. In any emergency, contact MRCC, a coastal
            radio station, or a shore-based medical authority as quickly as circumstances allow. The AI&rsquo;s
            guidance may be incomplete, outdated, or inapplicable to your specific situation — always exercise
            professional judgment and follow applicable maritime medical protocols.
          </p>
        </div>
      </div>

      <div className="space-y-8 text-sm text-slate-700 leading-relaxed">

        <section>
          <h2 className="text-base font-bold text-slate-900 mb-2">1. Acceptance of Terms</h2>
          <p>
            By accessing or using Vessel Ops AI (the &ldquo;Service&rdquo;), whether via the hosted web application,
            the desktop companion, or any future platform, you agree to be bound by these Terms of Use.
            If you do not agree, do not use the Service.
          </p>
        </section>

        <section>
          <h2 className="text-base font-bold text-slate-900 mb-2">2. What the Service Does</h2>
          <p>
            Vessel Ops AI is an offline-first AI assistant designed to support maritime medical triage and
            shipboard engineering operations. It draws on the WHO International Medical Guide for Ships
            (3rd Edition) and other embedded reference material to generate contextual guidance during
            voyages where professional medical care may not be immediately accessible.
          </p>
          <p className="mt-2">
            The Service is available in two modes:
          </p>
          <ul className="mt-2 list-disc list-inside space-y-1 text-slate-600">
            <li>
              <strong>Local mode</strong> — powered by Ollama running Gemma 4 entirely on your hardware.
              No data leaves your device.
            </li>
            <li>
              <strong>Cloud mode</strong> — hosted on Google Cloud Run with AI responses generated by Google
              Gemini via the Gemini API. Conversations are processed on Google&rsquo;s infrastructure.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-base font-bold text-slate-900 mb-2">3. No Medical or Legal Advice</h2>
          <p>
            Nothing produced by Vessel Ops AI constitutes medical advice, diagnosis, treatment, or a legal
            opinion. The Service is an aid — all clinical and operational decisions remain solely your
            responsibility. The creators, contributors, and operators of Vessel Ops AI expressly disclaim
            any liability for outcomes resulting from reliance on the Service.
          </p>
        </section>

        <section>
          <h2 className="text-base font-bold text-slate-900 mb-2">4. Permitted Use</h2>
          <p>You may use the Service for lawful maritime operations, training, and educational purposes. You must not:</p>
          <ul className="mt-2 list-disc list-inside space-y-1 text-slate-600">
            <li>Misrepresent AI-generated content as certified medical or engineering guidance.</li>
            <li>Attempt to reverse-engineer, scrape, or systematically extract the Service&rsquo;s knowledge base.</li>
            <li>Use the Service in any way that violates applicable laws or regulations, including SOLAS, STCW,
              or national maritime statutes.</li>
            <li>Attempt to gain unauthorised access to backend systems or databases.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-base font-bold text-slate-900 mb-2">5. Third-Party Content</h2>
          <p>
            The embedded WHO International Medical Guide for Ships (3rd Edition) is used under the terms
            established by the World Health Organization. Vessel Ops AI is not affiliated with or endorsed
            by the WHO. All trademarks remain property of their respective owners.
          </p>
        </section>

        <section>
          <h2 className="text-base font-bold text-slate-900 mb-2">6. Disclaimer of Warranties</h2>
          <p>
            The Service is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranties of any kind, express or implied,
            including but not limited to accuracy, fitness for a particular purpose, or uninterrupted availability.
            AI-generated content can contain errors. Verify all guidance against authoritative references before acting.
          </p>
        </section>

        <section>
          <h2 className="text-base font-bold text-slate-900 mb-2">7. Limitation of Liability</h2>
          <p>
            To the fullest extent permitted by law, the creators and operators of Vessel Ops AI shall not be
            liable for any direct, indirect, incidental, consequential, or special damages arising from your
            use of, or inability to use, the Service — including harm to persons, loss of life, property damage,
            or commercial loss.
          </p>
        </section>

        <section>
          <h2 className="text-base font-bold text-slate-900 mb-2">8. Changes to These Terms</h2>
          <p>
            We may revise these Terms from time to time. Continued use of the Service after changes are posted
            constitutes acceptance of the updated Terms. Material changes will be noted on this page with an
            updated revision date.
          </p>
        </section>

        <section>
          <h2 className="text-base font-bold text-slate-900 mb-2">9. Contact</h2>
          <p>
            Questions about these Terms can be directed to the Vessel Ops AI team via the project&rsquo;s
            GitHub repository.
          </p>
        </section>
      </div>

      {/* Footer links */}
      <div className="mt-12 pt-6 border-t border-slate-100 flex items-center justify-between text-xs text-slate-400">
        <div className="flex items-center gap-2">
          <Anchor size={14} />
          <span>Vessel Ops AI</span>
        </div>
        <div className="flex gap-4">
          <Link href="/privacy" className="hover:text-ocean-600 transition-colors">Privacy Policy</Link>
          <Link href="/" className="hover:text-ocean-600 transition-colors">Back to App</Link>
        </div>
      </div>
    </div>
  );
}
