"""initial

Revision ID: 13df8f5cdd90
Revises: 
Create Date: 2026-04-17 01:51:02.076699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13df8f5cdd90'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_queue',
    sa.Column('queue_id', sa.String(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.CheckConstraint("operation IN ('insert','update','delete')", name='ck_sync_operation'),
    sa.PrimaryKeyConstraint('queue_id')
    )
    op.create_table('vessels',
    sa.Column('vessel_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('imo_number', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('vessel_id')
    )
    op.create_table('components',
    sa.Column('component_id', sa.String(), nullable=False),
    sa.Column('vessel_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('system', sa.String(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('model_number', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('manual_ref', sa.String(), nullable=True),
    sa.Column('spare_parts', sa.Text(), nullable=True),
    sa.Column('photo_path', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("system IN ('propulsion','electrical','navigation','hvac','safety','hull')", name='ck_component_system'),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.vessel_id'], ),
    sa.PrimaryKeyConstraint('component_id')
    )
    op.create_table('crew_members',
    sa.Column('crew_id', sa.String(), nullable=False),
    sa.Column('vessel_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('blood_type', sa.String(), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('medical_notes', sa.Text(), nullable=True),
    sa.Column('emergency_contact', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.vessel_id'], ),
    sa.PrimaryKeyConstraint('crew_id')
    )
    op.create_table('health_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('vessel_id', sa.String(), nullable=False),
    sa.Column('crew_id', sa.String(), nullable=False),
    sa.Column('logged_by', sa.String(), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('vital_signs', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('protocol_used', sa.String(), nullable=True),
    sa.Column('ai_response', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('follow_up_required', sa.Boolean(), nullable=True),
    sa.Column('synced', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("severity IN ('minor','moderate','serious','critical')", name='ck_health_severity'),
    sa.ForeignKeyConstraint(['crew_id'], ['crew_members.crew_id'], ),
    sa.ForeignKeyConstraint(['logged_by'], ['crew_members.crew_id'], ),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.vessel_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('maintenance_logs',
    sa.Column('log_id', sa.String(), nullable=False),
    sa.Column('vessel_id', sa.String(), nullable=False),
    sa.Column('component_id', sa.String(), nullable=False),
    sa.Column('logged_by', sa.String(), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('issue_description', sa.Text(), nullable=True),
    sa.Column('photo_paths', sa.Text(), nullable=True),
    sa.Column('ai_diagnosis', sa.Text(), nullable=True),
    sa.Column('ai_guidance', sa.Text(), nullable=True),
    sa.Column('parts_used', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('follow_up', sa.Text(), nullable=True),
    sa.Column('synced', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("severity IN ('advisory','degraded','critical','down')", name='ck_maintenance_severity'),
    sa.ForeignKeyConstraint(['component_id'], ['components.component_id'], ),
    sa.ForeignKeyConstraint(['logged_by'], ['crew_members.crew_id'], ),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.vessel_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance_logs')
    op.drop_table('health_events')
    op.drop_table('crew_members')
    op.drop_table('components')
    op.drop_table('vessels')
    op.drop_table('sync_queue')
    # ### end Alembic commands ###
